config/routes.rb
Bookmarks::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :admin

  resources :books do
    member do
      get :new_comment
      get :comments
      post :create_comment
      delete '/comments/:comment_id' => "books#delete_comment"
    end
  end
  
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/book.rb
class Book < ActiveRecord::Base
   attr_accessible :title, :author, :id, :image
    has_attached_file :image,styles: { large: "2000x2000>",medium: "3000x3000>", thumb: "100x100>" }
   validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
   validates_presence_of :title
   validates_uniqueness_of [:title, :author]


  has_many :reviews , dependent: :delete_all
  has_many :comments , dependent: :delete_all
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :reviews
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :commentforbook
  belongs_to :book 
end

app/models/part.rb
class Part < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :title, :body
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
    Rails.logger.info "Books Path: #{books_path}\nBooks URL: #{books_url}\nBook Path: #{book_path(1)}\nBook URL: #{book_url(1)}\nEdit Book Path: #{edit_book_path(1)}\nEdit Book URL: #{edit_book_url(1)}}"
    @books = Book.all
   
	end

  def new
    @book = Book.new
  end

	def show
	  @book = Book.find(params[:id])
	  @reviews = @book.reviews
   end

   def create
    # @books= Book.all
    # @c=Book.all
    b = Book.new(params[:book])
    if b.save
      #redirect_to :action => :index
      flash[:alert] = "New Book Created"
      redirect_to :action=> 'index'  
      #success
    else
      flash[:alert] = "Book Creation Failed"
      redirect_to :action=> 'index'
      #failure
    end
    # b = Book.create(params[:book])

    # @book_new= Book.new(books_params) 
    #render 'books'
    
    # redirect_to books_path
    end

    def edit
      @book = Book.find(params[:id])

   end

    def update
      @book = Book.find(params[:id])
      if @book.update_attributes(params[:book])
         redirect_to :action => 'show' 
      else
         @reviews = Review.find(:all)
         render :action => 'edit'
      end
    end
    
    def new_comment
      @book = Book.find(params[:id])
      @comment =@book.comments.new
       
    end
    def create_comment
     @book = Book.find(params[:id])
     b =@book.comments.new(params[:comment])
     if b.save
        redirect_to :action => :comments
      else
        render :action => :new_comment
     #pending
    end
  end
    
    def comments
      @book = Book.find(params[:id])
      @comments = @book.comments
    end
    


    def destroy
     @book =Book.find(params[:id])
    
     if @book.destroy
      redirect_to action: 'index'
      flash[:success] = "Deleted!"
      
      else

      #render :json => {:success => 'true', :message => 'Book deleted!'}
     end
   end

     def delete_comment
      @book =Book.find(params[:id])
      @comments=@book.comments.destroy(params[:comment_id])
      # c= @comments.delete_comment(params[:comment_id])
      # if c.save
        redirect_to :action => :comments
      
      # end


    end

    # private 
    # def books_params
    # params.require(:book).permit(:title, :author, :image)
    # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/comments.html.erb
 <div id="a1">

  <% id1 = @book.id %>
<% @comments.each do |comment| %>

<% id2 = comment.id %>
<p id="a2"> <%= comment.commentforbook %> <%= link_to 'Delete Comment',  "/books/#{id1}/comments/#{id2}", method: :delete %><br></p>

<% end %> 
</div>

app/views/books/edit.html.erb
<div class="header">
  <div class="container">
   
    <h1>Edit Book</h1>
  </div>
</div>

<div class="create">
  <div class="container">
    
    <!-- Your code here -->
    <%= form_for @book,html: { multipart: true } do |b| %>  
  <div class="field"> 
    <%=b.label :title%> <%=b.text_field :title %><br> 
    <%= b.label :author %><%=b.text_field :author %><br>
    <%= b.label :image %> <%=b.file_field :image %>  
  </div> 
  <div class="actions"> 
    <%= b.submit "Update" %> 
  </div> 
<% end %>



  </div>
</div>

app/views/books/index.html.erb
 <div id="a1">
<% @books.each do |book| %>

  <div class="book">
    <div class="row">
      <div class="col-md-1">
        <p class="rank-this-week"> </p>
      </div>
      <div class="col-md-9">
        <p class="title"> <%= book.title %> </p>
        <p class="author"> by <%= book.author %>  </p>
        <p class="publisher"> <%= book.publisher %> </p>
        <p class="description"> <%= book.description %> </p>
        <p class="image"><%= image_tag book.image.url(:thumb)%> </p>
        <%= link_to 'See all Editorial Reviews', book %>
        <% id = book.id %>
        <%= link_to 'Edit Book', edit_book_path(book) %>
        <%= link_to 'AllComments', "/books/#{id}/comments" %>
        <%= link_to 'Comment', "/books/#{id}/new_comment" %>
        
        <%= link_to 'Delete', "/books/#{id}",method: :delete %>

        <!-- <a href="books/#{id}/edit">Edit Book</a> -->
      </div>
      <div class="col-md-2">
        <p class="weeks-on-list"> <%= book.weeks_on_list %></p>
      </div>
    </div>
  </div>
<% end %>
<%= link_to 'New Book', new_book_path %>
<!-- <a href="books/new">New Book</a> -->



</div>

app/views/books/new.html.erb
<div class="header">
  <div class="container">
   
    <h1>New Book</h1>
  </div>
</div>

<div class="create">
  <div class="container">
    
    <!-- Your code here -->
    <%= form_for @book,html: { multipart: true } do |b| %>  
  <div class="field"> 
    <%=b.label :title%> <%=b.text_field :title %><br> 
    <%= b.label :author %><%=b.text_field :author %><br>
    <%= b.label :image %> <%=b.file_field :image %> 
  </div> 
  <div class="actions"> 
    <%= b.submit "Create" %> 
  </div> 
<% end %>



  </div>
</div>

app/views/books/new_comment.html.erb
<div class="header">
  <div class="container">
   
    <h1>Comment The Book</h1>
  </div>
</div>

<div class="create">
  <div class="container">
    
    <!-- Your code here -->
    <%= form_for @comment , :url => { :action => 'create_comment', :controller => 'books' }  do |b| %>  
  <div class="field"> 
    <%=b.label :comment%> <%=b.text_field 'commentforbook' %><br> 
  </div> 
  <div class="actions"> 
    <%= b.submit "Create_comment" %> 
  </div> 
<% end %>



  </div>
</div>

app/views/books/show.html.erb
<div class="book">
 <% book = @book %>
  <p class="title"> <%= book.title %>  </p>
  <p class="author">by <%= book.author %>   </p>
  <p class="publisher"> <%= book.publisher %></p>
  <p class="description"><%= book.description %>  </p>
  <p class="image"><%= image_tag book.image.url(:large) %> </p>
  
</div>

<div class="reviews">
  <% @reviews.each do |review| %>
    <div class="review">
      <p class="author"> <%= review.author %>  </p>
      <p class="comment"> <%= review.comment %>  </p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

 
    
    
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    
    </div>
   
  <!-- <div class="alert alert-success">Deleted the book!</div> -->

</body>
</html>